### ISSUE TITLE
Не инициализируется sql файл, содержащий описание схемы БД

### ISSUE THREAD

**Issue by Evgeniya-EVA** [Evgeniya-EVA/mysqlSetUp#1]
# Шаги
1. Разместить в корне каталога проекта файл app-deadline.jar
2. Создать и разместить файл schema.sql в подкаталог /db
3. Создать файл docker-compose.yml:
```
version: '3.7'
services:
  mysqlContainer:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
```
4. Выполнить `docker-compose up`

# Ожидаемый результат:
Структура БД успешно создана

# Фактический результат:
Файл со схемой БД не прочитан. В логах присутствует следующая ошибка: "mysqlContainer_1  | ERROR: Can't initialize batch_readline - may be the input source is a directory or a block device.
"

# Окружение:
Windows 8.1 x64
Docker Toolbox for Windows
Mysql18.0.18
Intellij Idea CE 2019.2.3

# Скриншот:
![image](https://user-images.githubusercontent.com/58333040/76023650-97ef3680-5f3a-11ea-86d5-688447a84e18.png)

Помогите, пожалуйста, разобраться, в чем проблема!
